### ISSUE TITLE
Add optional callback for problem handling

### ISSUE THREAD

**Issue by upost** [undreamai/LLMUnity#127]
### Describe the feature

Currently, if the server does not start, you only produce a Debug.LogError(). That's fine for developing purposes, but if this happens on a customer machine, the error should be reported optionally to an object in the main game UI (using a callback or an event) so the game can display a meaningful message to the user.
Example: On one tester's machine, the MacAfee virus scanner isolated the llamafile executable during startup, so it was not there anymore, running the exe failed but the error did not show up anywhere, and Unity did not produce a crashlog. The problem was not visible to the user, the game just didn't work. 
As a workaround, I am now just regularly checking LLM.serverListening and show a generic message as long as this is false.

**Comment by amakropoulos** [comment]
Thank you that's a good idea, I will add it soon!

For which LLMUnity version did the MacAfee scanner complain?

**Comment by amakropoulos** [comment]
This is implemented in the upcoming release.
You can add a callback function to call on errors as follows:
```c#
void MyErrorCallBack(string message)
{
  Debug.Log(message);
}

LLMUnitySetup.AddErrorCallBack(MyErrorCallBack);
```

remove it when needed:
```
LLMUnitySetup.RemoveErrorCallBack(MyErrorCallBack);
```

or remove all:

```
LLMUnitySetup.ClearErrorCallBacks();
```
