### ISSUE TITLE
McAfee llamafile issue

### ISSUE THREAD

**Issue by Maapel** [undreamai/LLMUnity#128]
### Describe the bug

There is an issue with connecting to localhost.  The reason is probably the antivirus blocking the "llamafile-0.6.2.exe" , stating it has some virus. Due to this , the server is unable to start and so it's not getting connected. Turning off the antivirus works , but still without turning it off  , is there a way to solve this?

### Steps to reproduce

Run the sample scene in Unity. 

### LLMUnity version

1.2.4

### Operating System

Windows

**Comment by amakropoulos** [comment]
Hi, thanks for submitting the issue!
Which antivirus are you using?

llamafile is the "engine" that runs the LLMs in this package.
It is part of Mozilla Innovations and Experiments:
https://github.com/Mozilla-Ocho/llamafile
with >10000 stars on GitHub but some antivirus softwares still flag it.

Unfortunately there is not much I can do at the moment.
Can you try the 1.2.3 version of LLM for Unity that uses an earlier llamafile version and see if the antivirus complains for that?
You can download it from here:
https://github.com/undreamai/LLMUnity/releases/tag/v1.2.3
and import it as a local package in Unity.
Llamafile will release a new version hopefully soon as well, so fingers crossed!

**Comment by Maapel** [comment]
I am using McAfee. Using 1.2.3 version also raised the same issue . 

![image](https://github.com/undreamai/LLMUnity/assets/54804241/deb3a923-0723-416d-86ca-3a1ab019ab97)
![image](https://github.com/undreamai/LLMUnity/assets/54804241/d10d56d7-bb8e-4fdd-bb4a-1e4445342c54)

**Comment by amakropoulos** [comment]
Hi again! Llamafile v0.7 was released yesterday.
Could you try using the `feature/llamafile_v0.7` branch and see if the issue is still there?

**Comment by Maapel** [comment]
It still didn't work , the real-time scanning is deleting llamafile as soon as it is generated

**Comment by amakropoulos** [comment]
I submitted a form and McAfee has now whitelisted llamafile.
I tried with installing the antivirus and works for me now.
