### ISSUE TITLE
Insert temporary prompt

### ISSUE THREAD

**Issue by Legerdo** [undreamai/LLMUnity#131]
### Describe the feature

- Default Prompt

- Temp prompt <- No Save, But It is always above [User Prompt Input]

- User Prompt Input

- AI Response

[Temp prompt] is not saved, but should affect [AI Response] like [User Prompt Input].
Required to conserve token usage.
Is there any possible way?

**Comment by amakropoulos** [comment]
hi, thanks for the request!
what is the benefit of this approach? to process the Default Prompt only once and cache it?

You can use the `SetPrompt` function to change the prompt.
It includes a clearChat variable that specifies whether to clear the chat history and use only the prompt, or replace the system prompt.

To achieve the above you can do:
```c#
llm.SetPrompt("Default Prompt"+"Temp prompt", false)
```

**Comment by amakropoulos** [comment]
I see, thanks. I'm closing the issue, ping me if you have any other questions!
