### ISSUE TITLE
should we consider the possibility of including Google Gemini running on Vertex AI into this library?

### ISSUE THREAD

**Issue by david-wei-01001** [undreamai/LLMUnity#142]
### Describe the feature

I have written a small project to connect to Google Gemini within Unity. 
Should we consider the possibility of integrating a similar feature into this project as well?
https://github.com/david-wei-01001/CSharp-Unity-to-Google-Vertex-AI

As most models on Bloke cannot process image data, and stay as a text-only model, adding Gemini may provide the image and video feature into possible conversations

**Comment by amakropoulos** [comment]
Thanks a lot for the request!
It's a good idea, but I would like to keep the core of the package as open-source and free.
I'm reluctant about integrating paid solutions such as ChatGPT, Gemini etc
