### ISSUE TITLE
Saving the Chat Log

### ISSUE THREAD

**Issue by DinisB** [undreamai/LLMUnity#144]
### Describe the feature

Saving the chat log for the AI to remember in the future what conversation it had with the user.

**Comment by amakropoulos** [comment]
hi, thanks for the request!
I think this is related to this issue: https://github.com/undreamai/LLMUnity/issues/4
I'm actually currently working on this feature as part of https://github.com/undreamai/LLMUnity/issues/141 that will enable to save/restore interactions to disk.
