### ISSUE TITLE
Add support for Phi-3

### ISSUE THREAD

**Issue by Maskusa** [undreamai/LLMUnity#148]
### Describe the feature

Add support for Phi-3 and Llama-3

**Comment by amakropoulos** [comment]
Llama 3 support is implemented already in the latest version (v1.2.7).
I haven't tested yet phi3, will do that.

**Comment by Gabri94x** [comment]
hello there! any news? i tested and it was not supported in this version, i tried the new version of llama cpp and it run phi-3.
i tried to update the version on the plugin but without any result.

**Comment by amakropoulos** [comment]
hi, I'll look into it tomorrow!
I'll need to implement the phi-3 chat template as well.

**Comment by amakropoulos** [comment]
Sorry for the huge delay, I was deep into some DLL issues for another PR.
I'll release it today!

**Comment by Gabri94x** [comment]
@amakropoulos i'm sorry, i did not mean to interfere with your work. let me know if i can help you in any way!
btw thanks a lot for all of your work, you are doing really great job!

**Comment by amakropoulos** [comment]
not at all, thanks for pinging :)!

**Comment by amakropoulos** [comment]
@Gabri94x @Maskusa phi-3 support is now integrated and released, thank you for your patience!

**Comment by Gabri94x** [comment]
@amakropoulos thank you for your work. really appreciated!
