### ISSUE TITLE
LLM component continues to download model when removing it

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#153]
### Describe the bug

When removing the LLM component while it's downloading a model it will continue to download it. When adding it back while it's still downloading in the background it does not give any visual feedback on this. When selecting the model again, it will download it again. Weird stuff also happens when copying the component while it's downloading a model. I do not know a good way of fixing this. Maybe cancel active model downloads when the component is removed (if that is even possible)? Or even better check if a model is currently being downloaded before trying to download it (this would also help when having 2 LLM components for some reason: you click download on one and when clicking download on the second LLM component it will not download it since it's already being downloaded)

This is not too important since I do not believe anyone will ever try to copy or remove the component while it's downloading a model, but I think it's still a small bug to be aware of.

### Steps to reproduce

Add a LLM component in the scene and download any model. While it's downloading remove the component or copy and paste it.

### LLMUnity version

1.2.7

### Operating System

Windows

**Comment by amakropoulos** [comment]
I think this is not an issue anymore from v2.1.0 onwards because I implement my own downloader.
