### ISSUE TITLE
Phi 2 model has weird output when running on GPU

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#154]
### Describe the bug

When using the Phi 2 model and standard settings of the LLM model everything works fine. However, when I increase the `Num GPU Layers` It gets weird output.

`Num GPU Layers == 0 = normal`
`Num GPU Layers == 1 = normal`
`Num GPU Layers >= 2 = weird`

I have an RTX 3060 with cuda installed properly. The Mistral-7b-instruct model works fine no matter what value I use (above 30 my game starts to lag, but I think that's normal since it just uses more GPU)

I set the prompt of the LLM component to `You can only say "hello, this is a test"` and these are it's responses:
normal:
```
hello, this is a test
```
weird:
```
hello, this- " S M D B P TThe
-------------------------------------------------------- " S M D B P TThe
-------------------------------------------------------- " S M D B P TThe
-------------------------------------------------------- " S M D B P TThe
------------------------------------------------
```

As you can see, it's very strange. Sometimes it also uses symbols like `(` and `&` and so on which makes it look even stranger.

### Steps to reproduce

Open the chatbot sample and use the Phi 2 model. Adjust `Num GPU Layers` to see results

### LLMUnity version

1.2.7

### Operating System

Windows

**Comment by Maximilian-de-la-Mare** [comment]
This might be related to mmap within LLM.cs.

Attached is a fix for a similar issue I had. It needs to replace the "private async Task StartLLMServer()" section in LLM.cs, Line 342.

Please try it and let me know if this resolves the issue.

[LLM cs mmap Fix.txt](https://github.com/undreamai/LLMUnity/files/15439326/LLM.cs.mmap.Fix.txt)

**Comment by SubatomicPlanets** [comment]
Okay, thanks! I tried it, but it did not fix my issue. I looked more closely at the code and noticed that there is no difference between the fix and the source code (except for one removed comment). Did you maybe attach the wrong code? What exactly was your fix?

**Comment by Maximilian-de-la-Mare** [comment]
Weirdly enough, that was my fix. I'm not sure why my issue was fixed from that snippet, but it was. I do remember testing out Phi 2 with LM Studio and receiving garbage output. I recall others experiencing similar issues as well with Phi 2 using LM Studio, so it might be an issue with Phi 2 and the GGUF format.

**Comment by amakropoulos** [comment]
I can reproduce the issue but it has to be something with how llama.cpp handles GPU / CPU or how llamafile builds it.
I can't do anything but will check if the issue persists using the DLL functionality (#141)

**Comment by amakropoulos** [comment]
This seems to be resolved now with the latest llama.cpp / llamafile :+1:
