### ISSUE TITLE
Added History Function But Need To Clean

### ISSUE THREAD

**Issue by TKTSWalker** [undreamai/LLMUnity#161]
### Describe the feature

Hey, I added a sessions, save history and a few other smaller functions but I still need to clean them! They're very UI dependent right now but I plan on fixing that soon and then rolling the next big update next month!

Here is the link: https://github.com/Walker-Industries-RnD/Project-Replicant/tree/main

**Comment by amakropoulos** [comment]
Thanks for sharing, I love seeing projects using LLMUnity :heart: !
Saving functionality is implemented in the upcoming release v2.0.0 that saves the chat history as well as the LLM cache to avoid reprocessing the prompt.

**Comment by TKTSWalker** [comment]
Thank you for releasing this, I look forward to continuing the development of Project Replicant with LLMUnity! Hopefully my code can be of help to you!

**Comment by amakropoulos** [comment]
Great thank you, let me know if you get stuck with anything!
