### ISSUE TITLE
Saving LLMCharacters takes up a lot of storage space

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#167]
### Describe the bug

As far as I understand, saving a character saves the chat history and also the LLM cache. Is there a way to only save the History? 

The two files saved are a JSON, which I think is the history, and another file, which I think is the cache (I might be wrong). After just a minute of conversation, the cache file is 400 megabytes for one character alone. I guess not saving it will just increase the load times. Maybe there is also a more efficient way of saving it?

I know that most games will probably not have too many characters and I also guess it will stop increasing in size once the chat history limit is reached (if there is such a setting. I have not found it yet), but I love optimizing my games to use the least amount of storage possible, and this is a bit annoying.

### Steps to reproduce

- Create an LLMCharacter
- Make it save it's history and cache
- Look at the size of the cache file

### LLMUnity version

2.0.0

### Operating System

Windows

**Comment by amakropoulos** [comment]
The size of the cache file depends on the context size and can reach around this size.
I can't work around this, this is the way llama.cpp saves it.
It is also probably compressed in some way because zipping it further doesn't do much.

**Comment by amakropoulos** [comment]
The cache is needed otherwise the whole conversation will have to be recomputed from scratch

**Comment by SubatomicPlanets** [comment]
Okay, thanks. How long does it take to recompute a conversation? I know it will be very different depending on the context size, hardware and so on, but will it be around the time it takes to compute one request times the amount of requests the user made in the past?

**Comment by amakropoulos** [comment]
I added an option to save or not the LLM cache (or only the chat history).
The prompt processing can be split into 2 parts:
- prompt evaluation: this is quite faster and is affected by the LLM cache
- prompt response generation: this is slower and not affected
It really depends on the model how long you can save with the LLM cache, but a ballpark number is around doubling the prompt time.
You can evaluate the prompt by calling the `Warmup()` function though so you can manage that time during your loading process
