### ISSUE TITLE
LLMUnitySetup can be added as a component

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#168]
### Describe the bug

LLMUnitySetup inherits from MonoBehaviour and thus it can be added as a component in the inspector. I do not see any reason for this. I don't know if the inheritance can just be removed, or if it's a bit more complicated, but I don't think you should be able to add it as a component, right?

### Steps to reproduce

- Type llmunity into the add component menu. LLMUnitySetup will be shown there.

### LLMUnity version

2.0.0

### Operating System

Windows

**Comment by amakropoulos** [comment]
this is now resolved in the upcoming release
