### ISSUE TITLE
The editor crashes when exiting playmode while it is creating the LLM service

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#171]
### Describe the bug

This happens if asynchronous startup is true. When you exit playmode after the "Server command" log but before the "LLM service created" log, then the editor just closes.

### LLMUnity version

2.0.0

### Operating System

Windows

**Comment by stanchiang** [comment]
Same error. But happens regardless of async startup bool value. v1.2.9 example projects worked fine, but started a new project with 2.0.2 and they error out now.

LLMUnity Version
2.0.2

Operating System
Mac

**Comment by amakropoulos** [comment]
I can't replicate it so far.
@stanchiang do you get the crashes in general or only when you exit playmode before the llm is created?
