### ISSUE TITLE
Save the history in a seperate folder

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#177]
### Describe the feature

Save the chat history and cache in a separate folder. Like `Application.persistentDataPath + "History"` or something like that. Right now it just uses the persistentDataPath, but in my project, I would like it to be a bit more organized since I have many different things in that location.

I tried using paths in the save string, but that resulted in nothing being saved at all... Maybe it's the best solution to allow paths in that string, which then get appended to the persistentDataPath. That way, the developer has control over it.

**Comment by amakropoulos** [comment]
Certainly! I implemented the feature in #179, now the developer can pass relative paths as well in the save name.
I'll test it on Windows when the library is built and merge it to the next minor release.
