### ISSUE TITLE
Debug Log modes

### ISSUE THREAD

**Issue by SubatomicPlanets** [undreamai/LLMUnity#178]
### Describe the feature

Right now, it has a debug option that just logs more information. I have seen a nice feature in some other packages that I have, which is basically multiple log modes like "None", "All", "Error", and so on. It's a simple drop-down. I think this is useful because LLM for Unity always logs some text, but I would like to set it to log nothing or only errors when I test some other stuff in my game.
I don't know how complicated it is to add this, but if you haven't noticed already, I love small quality of life improvements :)

**Comment by amakropoulos** [comment]
It's the little things :slightly_smiling_face: !
Sure, I'll do that, should be easy
