### ISSUE TITLE
I get RAGSearchUnity cannot be found when I import the project

### ISSUE THREAD

**Issue by Mitko88** [undreamai/LLMUnity#191]
### Describe the bug

Assets\Samples\LLM for Unity\2.0.2\KnowledgeBaseGame\KnowledgeBaseGame.cs(8,7): error CS0246: The type or namespace name 'RAGSearchUnity' could not be found (are you missing a using directive or an assembly reference?)

### LLMUnity version

2022.3.22f1

### Operating System

Windows

**Comment by SubatomicPlanets** [comment]
Did you download the KnowledgeBaseGame sample from the package manager? If so, either remove it, or install the [RAGSearchUnity](https://github.com/undreamai/RAGSearchUnity) package. The reason for this error is that the KnowledgeBaseGame sample needs the RAGSearchUnity package to be installed.

**Comment by Mitko88** [comment]
Thank you for the quick response, I've downloaded the RAGSearchUnity package. However, I get another error this time:
Library\PackageCache\ai.undream.ragsearchunity@fea4ef9097\Runtime\Embedding.cs(316,101): error CS0122: 'Ops' is inaccessible due to its protection level

**Comment by amakropoulos** [comment]
Hi! You need to install it as in the instructions here:
https://github.com/undreamai/RAGSearchUnity?tab=readme-ov-file#setup
This is because it is a Unity asset that depends on other assets (Unity Sentis, Newtonsoft Json).

**Comment by Mitko88** [comment]
Yes, I followed the procedure, and I have Unity Sentis and Newtonsoft Json packages installed, but I get the error mentioned above

**Comment by amakropoulos** [comment]
Which Sentis version do you have?

**Comment by Mitko88** [comment]
I've tried to use 1.2, 1.4 and 1.5 version of Sentis and the error remains.

**Comment by amakropoulos** [comment]
Could you try with "1.2.0-exp.2" that the package is developed with?

**Comment by Mitko88** [comment]
I've tried with "1.2.0-exp.2" and it works. Thank you for the troubleshooting.

**Comment by amakropoulos** [comment]
Thank you for testing!
