### ISSUE TITLE
LLMClient Initialization Issue with OnEnable

### ISSUE THREAD

**Issue by BruceKristelijn** [undreamai/LLMUnity#20]
Hi there. I have tried implementing the project and it works very good so far. Thanks and props to you!
However in our project we create LLMClient's dynamically using `AddComponent`. However the usage of `OnEnable` causes some issues with this. `OnEnable` is called immediately when `gamobject.AddComponent` is called. Because of this settings the prompt has some issues.

I had this issue with Unity's own AudioSources aswell and a workaround I use is turning the game object off, adding the component and turning the gameobject on again.

```csharp
gameObject.SetActive(false);
llmclient = gameObject.AddComponent<LLMClient>();
llmclient.prompt = suspectInstance.Suspect.GeneratePersona();
gameObject.SetActive(true);
```

I would suggest using `Awake `or the `Start ` methods instead of `OnEnable` as there is no behaviour like `OnDisable`.

**Comment by amakropoulos** [comment]
Thank you for the contribution :clap: !
I didn't think about that, good point. 
I'd rather not add it in the Start because I'd like the server to start before any script calling it, but both `OnEnable` and `Awake` are both fine with me.
I'll test the PR and add it in v1.0.2!

**Comment by BruceKristelijn** [comment]
Thanks, about the start function is a great point! I am unsure is moving to awake is the best. What I was also thinking was maybe to create a setting like `enableOnAwake` or `startOnEnable` etc. That will be set true by default by the custom editor but the default value is `false`.

**Comment by amakropoulos** [comment]
Good point. I don't think there is a way to pass an argument when adding a component dynamically though (with `AddComponent<LLMClient>()`). 
I have added your implementation as well as your example in the Readme.md [here](https://github.com/undreamai/LLMUnity/pull/28).
Let me know if you have any comments!
