### ISSUE TITLE
ChatBot Sample Scene flow stuck on "Loading..."

### ISSUE THREAD

**Issue by kvarher** [undreamai/LLMUnity#21]
## Description
When Play Mode begins in the Unity Editor and after the LLM Server is started, the following two NullReferenceExceptions are thrown and the chat bubble in the scene is stuck on "Loading..."

NRE 1, which does not repeat:
> NullReferenceException: Object reference not set to an instance of an object
LLMUnitySamples.InputBubble.FixCaretSorting (UnityEngine.UI.InputField inputField) (at Assets/Samples/LLMUnity/1.0.1/ChatBot/Bubble.cs:183)
LLMUnitySamples.InputBubble..ctor (UnityEngine.Transform parent, LLMUnitySamples.BubbleUI ui, System.String name, System.String message, System.Int32 lineHeight) (at Assets/Samples/LLMUnity/1.0.1/ChatBot/Bubble.cs:144)
LLMUnitySamples.ChatBot.Start () (at Assets/Samples/LLMUnity/1.0.1/ChatBot/ChatBot.cs:49)

NRE 2, which repeats forever:
> NullReferenceException: Object reference not set to an instance of an object
LLMUnitySamples.ChatBot.Update () (at Assets/Samples/LLMUnity/1.0.1/ChatBot/ChatBot.cs:136)

## To Reproduce
- Load a model
- Enter Play mode in the Unity Editor

## Expected Behavior
- NREs do not appear
- User is able to interact with the scene

## Screenshots/Video
![Unity_Xs0YnNRMYJ](https://github.com/undreamai/LLMUnity/assets/154910532/5b8edb67-ea18-4e8f-840e-a58103019865)

## Configuration
 - Windows 10
 - Unity 2021.3.34 LTS
 - LLMUnity v1.0.1
 - Mixtral-8x7B-Instruct-v0.1-LimaRP-ZLoss-GGUF

## Notes
Thanks for creating this project. Great stuff!

**Comment by amakropoulos** [comment]
Thank you for submitting the issue :clap: !
It probably has to do with the Unity version, I have only tested from the latest 2022 LTS and 2023.
I'm downloading 2021.3.34 LTS and will include a fix in v1.0.2 ASAP!

**Comment by amakropoulos** [comment]
@kvarher version 2021 works now in v1.0.2!

**Comment by amakropoulos** [comment]
perfect :)!
