### ISSUE TITLE
LLM service couldn't be created with release 2.2.0

### ISSUE THREAD

**Issue by ltoniazzi** [undreamai/LLMUnity#223]
### Describe the bug

Installing the latest release and running a sample now raises `LLM service couldn't be created` for me.

### Steps to reproduce

1. Create new unity project
2. Install with git url from as in readme
3. Add `MultipleCharacters` sample and open scene
4. Download Qwen in `LLM`
5. Run game and get this error:

```txt
LLM service couldn't be created
UnityEngine.Debug:LogError (object)
LLMUnity.LLMUnitySetup:LogError (string) (at ./Library/PackageCache/ai.undream.llm@fa71fa39c5/Runtime/LLMUnitySetup.cs:149)
LLMUnity.LLM:StartLLMServer (string) (at ./Library/PackageCache/ai.undream.llm@fa71fa39c5/Runtime/LLM.cs:402)
LLMUnity.LLM/<>c__DisplayClass45_0:<Awake>b__0 () (at ./Library/PackageCache/ai.undream.llm@fa71fa39c5/Runtime/LLM.cs:119)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

### LLMUnity version

`2.2.0`

### Operating System

macOs

**Comment by amakropoulos** [comment]
Thank you, I'll check it out.
What Mac model do you have?

**Comment by ltoniazzi** [comment]
> What Mac model do you have?

Chip: Apple M2
MacOS: 14.5

**Comment by amakropoulos** [comment]
I will look into this on Monday

**Comment by amakropoulos** [comment]
Could you try with v2.2.1 or another sample?
There was an issue with parallel prompts. I doubt that it will solve your issue but just to make sure.

If it doesn't work could you do the following tests and let me know what works for you?

Test 1:
1. download and extract https://github.com/undreamai/LlamaLib/releases/download/v1.1.10/undreamai-v1.1.10-server.zip
2. copy the `macos-arm64-no_acc/undreamai_server` binary into your `Assets/StreamingAssets folder`
3. `cd` from cmd into the `Assets/StreamingAssets folder`
4. run `./undreamai_server -m <model_path>` and send me the output

Test 2:
1. download and extract https://github.com/undreamai/LlamaLib/actions/runs/10682409428/artifacts/1885738530
2. cd inside the <extracted directory>`/undreamai-RPC-llamacpp-macos-arm64-no_acc`
4. run `./undreamai_server -m <model_path>` and send me the output

Test 3:
1. download and extract https://github.com/ggerganov/llama.cpp/releases/download/b3617/llama-b3617-bin-macos-arm64.zip
2. cd inside the <extracted directory>`/build/bin`
3. run `./llama-server -m <model_path>` and send me the output

**Comment by ltoniazzi** [comment]
I tried now installing version `2.2.4` and samples seem to be working fine thanks! 😄

**Comment by amakropoulos** [comment]
Perfect thanks!
