### ISSUE TITLE
Build failing on Windows Intel 64-bit

### ISSUE THREAD

**Issue by 3inary** [undreamai/LLMUnity#227]
### Describe the bug

Building Library\Bee\artifacts\WinPlayerBuildProgram\qfds4\GameAssembly.dll failed with output:
   Creating library Library/Bee/artifacts/WinPlayerBuildProgram/qfds4/GameAssembly.dll.lib and object Library/Bee/artifacts/WinPlayerBuildProgram/qfds4/GameAssembly.dll.exp
gadbghvpbo0a.obj : error LNK2019: unresolved external symbol dlopen referenced in function Android_dlopen_m60F0347169BA153431E6A865033CFB3AA6D68304
gadbghvpbo0a.obj : error LNK2019: unresolved external symbol dlsym referenced in function Android_dlsym_m5B13C5684DEEBA7866FE7088600DCA5241C2EC35
gadbghvpbo0a.obj : error LNK2019: unresolved external symbol dlclose referenced in function Android_dlclose_mF9902015F50DB5D2B47247CA06ABB9B7894CD680
Library\Bee\artifacts\WinPlayerBuildProgram\qfds4\GameAssembly.dll : fatal error LNK1120: 3 unresolved externals

Uncommenting everything Android related in LLMLib resolves the issue.

### Steps to reproduce

Build on Windows

### LLMUnity version

current

### Operating System

Windows

**Comment by amakropoulos** [comment]
Thanks, I'll have a look on Monday

**Comment by amakropoulos** [comment]
Hi! I don't get this issue, but I may have found a fix.
Could you check if the `fix/android_linking_on_windows` branch works for you?

**Comment by amakropoulos** [comment]
This is now fixed in v2.2.2. The issue was specific to Windows IL2CPP builds, thanks for reporting!
