### ISSUE TITLE
Make LLMCharacter extendable

### ISSUE THREAD

**Issue by 3inary** [undreamai/LLMUnity#235]
### Describe the feature

Hi, i'd like to be able to define the json save (for ex. add a title) and to do so override the Load/Save functions.
To make this possible some signatures need to be modified in LLMCharacter:

protected string GetSavePath(string filename)
protected string GetJsonSavePath(string filename)
protected string GetCacheSavePath(string filename)
public/protected virtual async Task<string> Save(string filename)
public/protected virtual async Task<string> Load(string filename)
// protected async Task<string> Slot(string filepath, string action)

And in LLMCharacterEditor:
[CustomEditor(typeof(LLMCharacter), true)] // set to true to accept child classes as well

**Comment by amakropoulos** [comment]
Sure, will do that for the next release 👍
