### ISSUE TITLE
Do not expose system prompt in save file

### ISSUE THREAD

**Issue by 3inary** [undreamai/LLMUnity#236]
### Describe the feature

Hello, i'd like to not save/load the system prompt to/from file to exclude manipulation, is this possible?

**Comment by WillMiles** [comment]
A temporary solution before this gets implemented could be to just load the file after its been saved and then delete the system prompt manually?

**Comment by amakropoulos** [comment]
Very good idea! I'm implementing that now :+1:

**Comment by 3inary** [comment]
> A temporary solution before this gets implemented could be to just load the file after its been saved and then delete the system prompt manually?

With all due respect this is a terrible idea, how about not writing it in the first place?
The implemented solution it is also not working.

**Comment by amakropoulos** [comment]
They are not written in the version just released, v2.2.3.
Do I miss something?

**Comment by amakropoulos** [comment]
Maybe you had an existing save?

**Comment by 3inary** [comment]
Ah i see, i had to adapt my losd/save extension. Awesome, thaks!

**Comment by 3inary** [comment]
As for [#235](https://github.com/undreamai/LLMUnity/issues/235), i'd like to request to set set _private void InitPrompt(bool clearChat = true)_ in _LLMCharacter_ to protected.
