### ISSUE TITLE
Issue starting LLM

### ISSUE THREAD

**Issue by Eelguezabal** [undreamai/LLMUnity#249]
### Describe the bug

LLM fails to start up on a build on a laptop with these specs:

Processor: AMD Ryzen 5 7520U with Radeon Graphics
Video Card: AMD Radeon(TM) Graphics
Operating System: Windows 11
RAM: 16 GB

I thought at first it was maybe because its integrated graphics so I also tested with 0 GPU layers and it still didn't work.
I also noticed it fails because it tries every architecture but none work.

Thank you in advance!

Note: The version I am running is 2.2.2 but with some changes you recommended on this discussion post https://github.com/undreamai/LLMUnity/discussions/237

### LLMUnity version

2.2.2

### Operating System

Windows

**Comment by Eelguezabal** [comment]
Tested on another laptop with specs:

Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.80GHz
Video Card: GeForce GTX 1060
Operating System: Windows 10
RAM: 16 GB

On this laptop the game immediately shuts down with no crash, the logs just ended right after the "Server command" line aswell.

Was just testing a couple laptops, so I thought I would piggy back off my initial post.

Also as a sidenote this exact build of the game has been shown to work on 4 other machines.

**Comment by amakropoulos** [comment]
Hi! Are you running a sample?
If not, could you try e.g. with the SimpleInteraction sample?
Could you send me the logs of the failing PCs to see if there is some pattern?
It would really help if we could also do some troubleshooting on Discord.

**Comment by Eelguezabal** [comment]
So originally I was not running the sample, just an implementation for our game, but I did try it on both laptops.

For the first laptop these are the logs:
With GPU Layers 30 (Original Implementation): [With GPU Layers 30.log](https://github.com/user-attachments/files/17131898/With.GPU.Layers.30.log)
With GPU Layers 0 (Original Implementation): [With GPU Layers 0.log](https://github.com/user-attachments/files/17131905/With.GPU.Layers.0.log)
SampleInteraction: [Sample.log](https://github.com/user-attachments/files/17131922/Sample.log)

For the second laptop I decided to test with GPU Layers equal to 0 and the SampleInteraction scene and both worked, however generation was slow (which i guess there's no getting around because maybe the laptop doesn't have enough VRAM). Either way here is that original log when it wasn't working in my original implementation:

[2nd Laptop.log](https://github.com/user-attachments/files/17132008/2nd.Laptop.log)

And yes I am definitely open to troubleshooting on discord!

**Comment by amakropoulos** [comment]
I'm on Discord if you would like to have a discussion now: https://discord.gg/RwXKQb6zdv

**Comment by Eelguezabal** [comment]
Give me around one hour and i'll join

**Comment by amakropoulos** [comment]
hi! I'm closing this issue, there is an open issue on AMD (#202 ) for which you are still facing some issues.
