### ISSUE TITLE
[Android build] IOException: The file exists

### ISSUE THREAD

**Issue by siduko** [undreamai/LLMUnity#262]
### Describe the bug

When I build the demo android sample, It's successfully at first time, but I rebuild, it will show the error

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/2139b2a6-8aa0-4524-aa21-b23998fdd0d1">

### Steps to reproduce

1. Build to apk, and installed
2. Rebuild but it can not because the error

### LLMUnity version

2.2.4

### Operating System

Windows

**Comment by amakropoulos** [comment]
Hi! This could be due to an interrupted build.
Could you try again after deleting this folder?
`C:\Users\[USER]\AppData\Local\Temp\[COMPANY]\[PROJECT]\LLMUnityBuild`
The company name will be "DefaultCompany" if you haven't specified it in Unity

**Comment by amakropoulos** [comment]
The above solution should resolve the issue, let me know if you still face it

**Comment by ate864** [comment]
Same happen to me on unity 6000.0.24f1. Need to restart my computer to build (and not clic on play button before). 
I got the error even if i restart unity, directly whene scene open in editor.

IOException: Le fichier existe
System.IO.FileSystem.MoveFile (System.String sourceFullPath, System.String destFullPath) (at <321eb2db7c6d43ea8fc39b54eaca3452>:0)
System.IO.File.Move (System.String sourceFileName, System.String destFileName) (at <321eb2db7c6d43ea8fc39b54eaca3452>:0)
LLMUnity.LLMBuilder.HandleActionFileRecursive (System.String source, System.String target, LLMUnity.ActionCallback actionCallback) (at Assets/LLMUnity/Runtime/LLMBuilder.cs:37)
LLMUnity.LLMBuilder.HandleActionFileRecursive (System.String source, System.String target, LLMUnity.ActionCallback actionCallback) (at Assets/LLMUnity/Runtime/LLMBuilder.cs:47)
LLMUnity.LLMBuilder.MovePath (System.String source, System.String target) (at Assets/LLMUnity/Runtime/LLMBuilder.cs:79)
LLMUnity.LLMBuilder.MoveAction (System.String source, System.String target, System.Boolean addEntry) (at Assets/LLMUnity/Runtime/LLMBuilder.cs:118)
LLMUnity.LLMBuilder.Reset () (at Assets/LLMUnity/Runtime/LLMBuilder.cs:204)
LLMUnity.LLMBuildProcessor.<BuildCompleted>b__5_0 () (at Assets/LLMUnity/Editor/LLMBuildProcessor.cs:58)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <5d5fdc1eeb2a4f39b26caadc7b79ec7e>:0)

**Comment by amakropoulos** [comment]
can you also delete the Assets/StreamingAssets/undream* folder, restart Unity and wait for it to be downloaded again?

**Comment by ate864** [comment]
ok i deleted temp folder and streamingAssets content folder, restart unity , it start downloading zip file in temp folder, extract it in streamingassets folder, remove the zip file from temp folder, "Download Complete"
i click play mode (android demo scene) > all is ok no error.
Build on android > UnauthorizedAccessException: Access to the path 'undreamai_windows-avx2.dll' is denied.
the temp folder get all the platforms but the streaminasset folder can't be totaly empty, it stay some platforms with windows-avx2.
The LLMBuilder.cs script can't remove the undreamai_windows-avx2.dll , need to stop it before .

**Comment by ate864** [comment]
Maybe ? https://www.forrestthewoods.com/blog/debugging-a-dynamic-library-that-wouldnt-unload/

**Comment by amakropoulos** [comment]
Thank you! I free the library [here](https://github.com/undreamai/LLMUnity/blob/main/Runtime/LLMLib.cs#L408).
It needs some investigation..

**Comment by ate864** [comment]
yes :) , that why i think about looking inside the dll.... 
thank you to look at it !
