### ISSUE TITLE
Increase AI answer speed ?

### ISSUE THREAD

**Issue by al3dv2** [undreamai/LLMUnity#269]
### Describe the feature

Hi, I’d like to know how to have the AI's text display fully and as quickly as possible when it responds, because I’m using text-to-speech, and the pronunciation is slowed down by the typing speed. What should I change to display the entire text quickly? Thanks

**Comment by amakropoulos** [comment]
To show the full reply only when generated you can disable the `stream` parameter of the LLMCharacter.

It will not speed up the reply though, when `stream` is enabled it just shows the incomplete response while it is being generated.
Disabling it will only show it when complete.
