### ISSUE TITLE
Failed to load library .../archchecker.dll on x32

### ISSUE THREAD

**Issue by CGAleksey** [undreamai/LLMUnity#276]
### Describe the bug

I created a build for Windows x32 and noticed that archchecker.dll only works for x64.
When I run the application, I see an error in Player.log:
_Failed to load library F:/LLM_Data/StreamingAssets/undreamai-v1.1.12-llamacpp\windows-archchecker/archchecker.dll._

### Steps to reproduce

Use target platform: Windows
Target architecture: Intel x32
Click on "Build". Run the assembled project and look at Player.log
![99](https://github.com/user-attachments/assets/c2f80cdc-779c-4736-9c3e-93b846655a39)

### LLMUnity version

2.3.1

### Operating System

Windows

**Comment by amakropoulos** [comment]
Hi, yes indeed, I only support x64 at the moment because x32 is very rare.
What kind of system/ usecase do you need it for?
I believe I can build it for x32

**Comment by amakropoulos** [comment]
Hi again! I won't support 32-bit architectures for some time at least.
It will need some effort to implement and the benefit will be limited compared to other features as there are no recent systems with this architecture (as far as I know at least).
Also I can't test it as I don't have such a device or find one on the cloud
