### ISSUE TITLE
Failed to load library ios.

### ISSUE THREAD

**Issue by sam598** [undreamai/LLMUnity#286]
### Describe the bug

Service fails to load and never moves past "Warming up the model."

Key error seems to be "Tried architecture: ios, error: System.Exception: Failed to load library ios."

```
Download complete!
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
LLMUnity.<DownloadFile>d__27:MoveNext()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()

Deploy server command: ./undreamai_server -m "/var/mobile/Containers/Data/Application/BC1B8225-CFF9-455A-BFEE-EBD870986279/Documents/llama-3.2-1b-instruct-q4_k_m.gguf" -c 8192 -b 512 --log-disable -np 1 -ngl 0 --template "llama3 chat"
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
LLMUnity.LLM:GetLlamaccpArguments()
LLMUnity.<Awake>d__53:MoveNext()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task`1:TrySetResult(TResult)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
LLMUnity.<SetupOnce>d__12:MoveNext()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Threading.Tasks.AwaitTaskContinuation:RunCallback(ContextCallback, Object, Task&)
System.Threading.Tasks.Task:FinishContinuations()
System.Threading.Tasks.Task`1:TrySetResult(TResult)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult(TResult)
LLMUnity.<DownloadFile>d__27:MoveNext()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()

Tried architecture: ios, error: System.Exception: Failed to load library ios.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
LLMUnity.LLM:StartLLMServer(String)
System.Threading.Tasks.Task:Execute()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
System.Threading.Tasks.Task:ExecuteEntry(Boolean)
System.Threading.ThreadPoolWorkQueue:Dispatch()

LLM service couldn't be created
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
LLMUnity.LLMUnitySetup:LogError(String)
LLMUnity.LLM:StartLLMServer(String)
System.Threading.Tasks.Task:Execute()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
System.Threading.Tasks.Task:ExecuteEntry(Boolean)
System.Threading.ThreadPoolWorkQueue:Dispatch()
```

The Plugins/Android folder is empty. I'm not sure if there is supposed to be something for ios?

### Steps to reproduce

1) Started a new Unity Project (6000.0.26f1 Silicon)
2) Made sure "StreamingAssets" and "Plugins/Android" folders existed
3) Installed latest version through package manager + git 
4) Imported mobile scene, add it to build settings
5) Downloaded Llama 3.2 1B
6) Checked "Download on start"
7) Built for ios
8) Model download, progress bar is visible
9) Screen remains on "Warming up the model".

### LLMUnity version

2.4.0

### Operating System

macOs

**Comment by sam598** [comment]
I see that there is a file:

`StreamingAssets/undreamai-v1.2.0-llamacpp/iOS/libundreamai_iOS.dylib`

But if I copy it to:

`Plugins/iOS/libundreamai_iOS.dylib`

In xcode the build fails with this error:

`Library 'undreamai_iOS' not found`

**Comment by sam598** [comment]
Copied:

`Packages/ai.undream.llm/Resources/usearch/iOS/libusearch_static_c.a`

To:

`Plugins/iOS/libusearch_static_c.a`

I no longer get the xcode error, but the build still fails with the same error as before:

```
Tried architecture: ios, error: System.Exception: Failed to load library ios.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
LLMUnity.LLM:StartLLMServer(String)
System.Threading.Tasks.Task:Execute()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.Tasks.Task:ExecuteWithThreadLocal(Task&)
System.Threading.Tasks.Task:ExecuteEntry(Boolean)
System.Threading.ThreadPoolWorkQueue:Dispatch()
```

**Comment by amakropoulos** [comment]
Hi! What iOS device are you trying this on?
You don't need to copy any plugins, I do that automatically.
The plugins should be in the following build dirs:
- Data/Raw/undreamai-v1.2.0-llamacpp/iOS/libundreamai_iOS.dylib
- Libraries/LLMUnity/Resources/usearch/iOS/libusearch_static_c.a

**Comment by sam598** [comment]
iPhone 14 Pro Max

In the xcode project this exists:

`Data/Raw/undreamai-v1.2.0-llamacpp/iOS/libundreamai_iOS.dylib`

But this does not:

`Libraries/LLMUnity/Resources/usearch/iOS/libusearch_static_c.a`

I think this is because I installed it through package manager, as the asset store version is not setup for 2.4.0 yet. If I make this path in the unity project:

`Assets/LLMUnity/Resources/usearch/iOS/libusearch_static_c.a`

Then this does appear in the xcode project:

`Libraries/LLMUnity/Resources/usearch/iOS/libusearch_static_c.a`

But I still get the error:

`Tried architecture: ios, error: System.Exception: Failed to load library ios.`

**Comment by amakropoulos** [comment]
The libusearch_static_c.a is in the Resources folder already: https://github.com/undreamai/LLMUnity/blob/main/Resources/usearch/iOS/libusearch_static_c.a
so probably something to do with the package manager, yes.
But anyway the libusearch_static_c.a is only needed for the RAG, the LLM should work.

how do you install it on the device?
I tested on a iPhone 14 Pro Max on AWS Device Farm and it worked for me.
The way I did it was to create an ipa and install it on the device.
You can find this test ipa [here](https://github.com/undreamai/LlamaLib/actions/runs/12123449683/artifacts/2262533068).

Would you like to have a call or chat on [discord](https://discord.gg/RwXKQb6zdv) for quicker resolution?

**Comment by sam598** [comment]
Generally it would be better to share the unity or xcode project (with your apple profiles removed) instead of an ipa. Sideloading to a device is not quite on the same with Apple as it is on Android, and signing packages for compiled apps is much more complicated and risky.

I'll try out a few more things and reach out on discord.

**Comment by amakropoulos** [comment]
Sure, I didn't do anything interesting 👍.
I just built the MobileDemo sample with the Qwen 2 0.5B model.

**Comment by whynames** [comment]
I get the same error, on IPhone 13 Pro, Tried architecture: ios, error: System.Exception: Failed to load library ios.

**Comment by amakropoulos** [comment]
I'm working on it, the problem is that the undreamai library is unsigned.
One workaround is to sign the library yourself (undreamai_iOS.dylib).
I'm trying to now implement it as a static library instead of dynamically linking it so that it is baked into the app and doesn't need external signing.
If you are interested, there is a thread on the ios channel on discord.

**Comment by whynames** [comment]
Thanks, I read the thread. I am not sure about how to sign it? With the command you shared on discord? From  terminal, or from Xcode, the one located in unity streaminga, or xcode build?

**Comment by amakropoulos** [comment]
I will ask there not sure.
Otherwise static linking should be done very soon (this week) :+1:

**Comment by whynames** [comment]
I got these errors, xcode build fails
<img width="257" alt="Screenshot 2024-12-17 at 15 20 06" src="https://github.com/user-attachments/assets/e09a533b-b811-4502-85a4-ad00e7548292" />

**Comment by amakropoulos** [comment]
is this with the `feature/static_library_linking_on_mobile` branch?

**Comment by amakropoulos** [comment]
I use this command to build the project and it works for me:
xcodebuild clean archive \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath $PWD/build/Unity-iPhone.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=<MY_TEAM_ID>

**Comment by whynames** [comment]
> is this with the `feature/static_library_linking_on_mobile` branch? do you have any errors during the ios build in unity? Can you check if you have a `libundreamai_ios.a` file inside `Libraries/Plugins/iOS/LLMUnity/undreamai-v1.2.0-dev-llamacpp` of the xcode project created?

Yes it was



> I use this command to build the project and it works for me:
> 
> ```
> xcodebuild clean archive \
>             -project Unity-iPhone.xcodeproj \
>             -scheme Unity-iPhone \
>             -configuration Release \
>             -destination "generic/platform=iOS" \
>             -archivePath $PWD/build/Unity-iPhone.xcarchive \
>             CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=<MY_TEAM_ID>
> ```

 I don't think app store allows games without signing. I don't use terminal commands, I build from xcode, and it asks for a development team. It builds with the main branch, but can't find llm, build problem only with this one.

**Comment by amakropoulos** [comment]
Sure, you can sign it.
I do it like that for testing purposes, I don't have a developer account.
With the main branch the library is shipped inside the project and dynamically loaded at runtime, while with this branch it is embedded and build with the project.

Do you find the libundreamai_ios.a inside the xcode project?

**Comment by whynames** [comment]
No, it is not there, I will try a clean build again now
