### ISSUE TITLE
Weird performance on RTX 2060 super

### ISSUE THREAD

**Issue by BruceKristelijn** [undreamai/LLMUnity#29]
Hi there. Was very suprised by the speed of this implementation. However is doesn't work on my colleagues PC. The server starts when GPU layers is set to 35 but interfacing takes a massive amount of time and after sending a prompt the model goes into some sort of loop, repeating the same output till the limit is reached. We have tried different settings but to no avail. 

Specs:
- Windows 11
- Nvidia RTX 2060 Super GPU (With the latest game ready drivers)
[log.txt](https://github.com/undreamai/LLMUnity/files/13939786/log.txt)

- Settings: All settings are default out of the box
- Model: `mistral-7b-instruct-v0.2.Q4_K_M.gguf`

I will include the logs. We have compared the logs and output on both machines, but these do not seem all that different aswell.

**Comment by BruceKristelijn** [comment]
[log.txt](https://github.com/undreamai/LLMUnity/files/13939788/log.txt)

**Comment by amakropoulos** [comment]
Hi again, thanks for submitting the issue!
How does your call to `Chat` look like?
From the logs it seems as if the prompt evaluation is really slow, while the response evaluation time is ok.
Not sure why.
Can you try setting the GPU layers to a lower value e.g. 10?

**Comment by BruceKristelijn** [comment]
We have tried setting it to other values like 0 and 10 but that made the server crash on start (I think). I will provide the logs later but it's so weird why it happens. Both systems have the same cuda system. Could it be that I pushed the exe of the server from the 1606 machine? That the other system needs to download these itself?

**Comment by amakropoulos** [comment]
no that would be fine. ok let me know :)

**Comment by BruceKristelijn** [comment]
So the Chat looks like this:

```csharp
string response = "";
await llmclient.Chat(message, (s) => response = s);
```

These are the logs when less gpu layers are set:
[crash_0_gpulayer.txt](https://github.com/undreamai/LLMUnity/files/13961411/crash_0_gpulayer.txt)
[crash_10_gpulayers.txt](https://github.com/undreamai/LLMUnity/files/13961426/crash_10_gpulayers.txt)

Hope you are able to help me find a solution since I have no clue what could be causing this!

**Comment by BruceKristelijn** [comment]
I have done more testing an figured something out:
Both machines reach this point `llm_load_tensors: offloaded 33/33 layers to GPU`

However while the working one works the 2070 machine logs this:
`GGML_ASSERT: llama.cpp/ggml-backend.c:1276: (char *)addr + ggml_backend_buffer_get_alloc_size(buffer, tensor) <= (char *)ggml_backend_buffer_get_base(buffer) + ggml_backend_buffer_get_size(buffer)`
And logs `GPU Failed, fallback to CPU`

When I find something more I will report back. There is enough memory left so I am sure that's not it.

**Comment by BruceKristelijn** [comment]
While there seems to be enough memory left on both the CPU and GPU the C code indicates a memory check (it is logged last on both the running for CPU & GPU). I am not very versed in C so I might be wrong.

**Comment by amakropoulos** [comment]
Thank you for the detailed replies and logs!
I went through them and find the following error:
`llama.cpp/ggml.c:9067: [31;1massert(!isnan(x)) failed[0m (cosmoaddr2line /P/Development Games/ai_interrogation/unityproject/Assets/StreamingAssets/llamafile-server.exe 4c54f9 4e3982 4e7379 5c9afc 5e7b93)`

I searched on llamafile issues and these 2 seem related:
https://github.com/Mozilla-Ocho/llamafile/issues/146
https://github.com/Mozilla-Ocho/llamafile/issues/104

Can you try to modify this line:
https://github.com/undreamai/LLMUnity/blob/main/Runtime/LLM.cs#L236
to:
_string GPUArgument = numGPULayers <= 0 ? "" : $" -ngl {numGPULayers}  **--no-mmap**";_

and let me know if it works?

**Comment by BruceKristelijn** [comment]
I just tried this solution on another pc where it didn't work and there it actually did! I will get back asap when I tested it on the other pc. I noticed the first prompt however took a little longer (We do warm up however), could that be because of the flag?

**Comment by BruceKristelijn** [comment]
This works, thank you so much!

**Comment by BruceKristelijn** [comment]
> Perfect, thanks! I need to test the warm-up time. I will add a solution that uses this flag if it fails with the specific message. For the time being you can use that option :). I'll keep the issue open and will close it when implemented,

Great. If you need any logs, tests etc. Let me know!

**Comment by amakropoulos** [comment]
In v1.0.5 I check for the error and run with "--no-mmap" if it fails for that reason.
I don't have the specific GPU to test it but I simulated the error, hope it works :)!
