### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by amakropoulos** [undreamai/LLMUnity#40]
Purpose of this features is to add support of LLMUnity for Android

Issues:
- llamafile does not support Android, the llama.cpp server binary will need to be separately compiled
- Android needs separate implementation for starting and possibly communicating to the server

An experimental WIP branch is `feature/android_support`

**Comment by al3dv2** [comment]
Yes please add android that would be awesome !

**Comment by al3dv2** [comment]
I don't see the experimental branch, where I can download it ? thanks "feature/android_support"

**Comment by amakropoulos** [comment]
Ah I was trying something but deleted it, didn't really progress.

**Comment by al3dv2** [comment]
Oh ok do you thinks it's possible to have unity LLM on android ? thks

**Comment by amakropoulos** [comment]
At some point, but I think it's going to need implementation effort

**Comment by yumianhuli2** [comment]
> At some point, but I think it's going to need implementation effort

Hello! Do you have this plan for android support?

**Comment by amakropoulos** [comment]
Yes! I'm actually doing some tests right now, but can't yet promise on dates

**Comment by yumianhuli2** [comment]
> Yes! I'm actually doing some tests right now, but can't yet promise on dates

Oh, thanks my God

**Comment by ropenrom24** [comment]
Hi @amakropoulos can you give us the high level stuff on how would you implemented this? I see that your using a process to start a server from `llamafile-0.6.2.exe` which is from this [repository](https://github.com/Mozilla-Ocho/llamafile). But how would this be implemented on android? thanks.

**Comment by amakropoulos** [comment]
Sure, this feature will be built after #141 which will replace llamafile with directly integrated DLLs.
Android is supported by llama.cpp so after that I'll build a DLL specific for Android to serve the functionality.
And then fingers crossed :)!

**Comment by amakropoulos** [comment]
closed by #197
