### ISSUE TITLE
Remember optimal server settings

### ISSUE THREAD

**Issue by BruceKristelijn** [undreamai/LLMUnity#69]
### Describe the feature

With the introduction of the fallback to `CPU `and `--no-mmap` I was thinking. Maybe start up can be sped up on a repeated run by remembering what setup worked for this user? So the first time the LLM.cs will recognise what works and the other times a user starts up the game it will run in these settings. 

I am unsure how to implement this yet (how / where to store this?) and probably something for the future but can help speed up launch times for users.

**Comment by amakropoulos** [comment]
Very good point! I think something like this can be implemented with [PlayerPrefs](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html).

**Comment by BruceKristelijn** [comment]
PlayerPrefs are an option but as a developer I try to not use them in production. These seem to be saved in some (in my opinion) odd [places](https://discussions.unity.com/t/where-is-playerprefs-located-on-windows/7278/3). I problem I forse with PlayerPrefs is that when something does not work for the end-user it is a bit harder to help them reset the settings themselves. It would seem more elegant to tell them to go to to [Application.persistentDataPath](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html) and remove a certain file so LLMUnity can generate new ones? Let me know what you think!

**Comment by amakropoulos** [comment]
Yes you are right, that's better!

**Comment by amakropoulos** [comment]
I think the functionality is not needed anymore with the DLLs because they either load or not depending on the system hardware.
