### ISSUE TITLE
Some mac need to run the command manually to work

### ISSUE THREAD

**Issue by amakropoulos** [undreamai/LLMUnity#85]
### Describe the bug

For some reason the llamafile command doesn't work within unity unless the command is first run manually.
Need to investigate how to fix that and if it applies to the builds as well

### Operating System

macOs

**Comment by ilanb** [comment]
Confirmed on MB Pro 2,3 GHz Intel Core i9 8 cœurs AMD Radeon Pro 5500M 4 Go 16 Go 2667 MHz DDR4 
Ventura 13.4 (22F66)

I need to launch on terminal:

sh -c "/Users/ilan/_INFOSTRATES/_PONANT/LLMPonant/Assets/StreamingAssets/llamafile-0.6/bin/llamafile  --port 13333 -m /Users/ilan/_INFOSTRATES/_PONANT/LLMPonant/Assets/StreamingAssets/mistral-7b-instruct-v0.2.Q4_K_M.gguf -c 512 -b 512 --log-disable --nobrowser -np 1"
