### ISSUE TITLE
Test Windows IL2CPP

### ISSUE THREAD

**Issue by amakropoulos** [undreamai/LLMUnity#86]
Test if the Process works for Windows IL2CPP:
https://forum.unity.com/threads/solved-il2cpp-and-process-start.533988/

otherwise implement a specific solution like:
https://github.com/josh4364/IL2cppStartProcess/tree/master

**Comment by SubatomicPlanets** [comment]
Hey, I just wanted to let you know that IL2CPP support is very important to me. I hope you can implement it soon if it's not too complicated. Thanks! Great project by the way!

**Comment by amakropoulos** [comment]
Thank you!
The problem with IL2CPP is that it doesn't support processes.
I am now working on implementing the LLM backend with DLLs which should alleviate most of the problems.
Then I will test and see what are the remaining issues to support IL2CPP.

**Comment by SubatomicPlanets** [comment]
Just tested the 2.0.0 release and IL2CPP seems to be working fine! I tested all the included models both on cpu and gpu and I see no errors or warnings in the build or in the editor. There appears to be no difference between IL2CPP and mono anymore!
