### ISSUE TITLE
Text Completions

### ISSUE THREAD

**Issue by IkariDevGIT** [undreamai/LLMUnity#99]
### Describe the feature

Please for the love of god add Text completions support, chat complations is ass for anything non chat related.

**Comment by amakropoulos** [comment]
Hi, what do you mean by text completion?
You can provide the prompt in a way to do that no?
No need for frustration btw ;)

**Comment by IkariDevGIT** [comment]
@amakropoulos Im not frustrated, it's just some meming don't take it seriously lol.
I would also suggest adding support for gen settings if it's not already implemented

Text completions is basically just completing a text, for example here some pseudo code to demonstrate it:
```python
settings = {...}
str1 = "Once apon a time there was a guy named "
print(llm.Complete(str1, settings))
```
Output would be:
```
eric, he loved singing.
```

**Comment by amakropoulos** [comment]
I see thanks! The completion should be easy to add, I'll mark it for the next release.
In terms of gen settings what are you interested in more specifically?
There are quite a few options in Model settings (see advanced and expert options [here](https://github.com/undreamai/LLMUnity?tab=readme-ov-file#options))

**Comment by amakropoulos** [comment]
@IkariDevGIT you can now do pure text completion with `llm.Complete`, see the README on how to use it
